---
engine_version: 0.4.20
file_version: 2023-07-24 13:51:23.939989000 Z
resources: []
configs:
- key: header.links
  value:
  - name: "⭐ Star on GitHub"
    path: https://github.com/motor-admin/motor-admin-rails
  updated_at: 2023-07-24 13:49:51.658537000 +00:00
- key: homepage.layout
  value: []
  updated_at: 2023-07-24 13:51:23.939989000 +00:00
queries: []
dashboards: []
forms: []
alerts: []
api_configs:
- id: 1
  name: origin
  url: "/"
  preferences: {}
  description: 
  updated_at: 2023-07-24 13:49:51.666293000 +00:00
